# Generated by Django 3.0.7 on 2020-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voyageurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=15)),
                ('nationalite', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=25)),
            ],
        ),
    ]
