# Generated by Django 3.0.7 on 2020-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
