# Generated by Django 3.0.7 on 2020-10-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
    ]
