# Generated by Django 3.0.7 on 2020-12-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0007_auto_20201125_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vols',
        ),
        migrations.DeleteModel(
            name='voyageurs',
        ),
    ]
