# Generated by Django 3.0.7 on 2020-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutu', '0008_auto_20201203_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cover',
            field=models.FileField(upload_to='image/picture'),
        ),
    ]
